[package]
name = "rain"
version = "0.1.0"
authors = ["mvidigueira <mvidigueira@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drop = { path = "/home/manuel/Documents/M4/rust_playground/drop" }
macros = { path = "/home/manuel/Documents/M4/rust_playground/drop/macros" }
merkle = { path = "../merkle" }
wasm_contracts_common = { path = "../wasm_contracts_common" }
classic = { path = "/home/manuel/Documents/M4/rust_playground/classic" }
serde = "1.0.102"
tokio = "0.2.0"
futures = "0.3.4"
tracing = "0.1.13"
tracing-futures = "0.2.3"
bincode = "1.2.1"
log = "0.4"

[dev-dependencies]
tracing-subscriber = "*"