[package]
name = "rain"
version = "0.1.0"
authors = ["mvidigueira <mvidigueira@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drop = { path = "/home/manuel/Documents/M4/rust_playground/drop" }
macros = { path = "/home/manuel/Documents/M4/rust_playground/drop/macros" }
merkle = { path = "../merkle" }
# classic = { path = "/home/manuel/Documents/M4/rust_playground/classic" }
tokio = "0.2.0"
futures = "0.3.4"
tracing = "0.1.13"
tracing-futures = "0.2.3"

[dev-dependencies]
tracing-subscriber = "*"