[package]
name = "contract_test"
version = "0.1.0"
authors = ["mvidigueira <mvidigueira@gmail.com>"]
edition = "2018"

[lib]
crate-type = ['cdylib']

[profile.release]
lto = true
opt-level="s"
panic = "abort"

[dependencies]
wasm-bindgen = "0.2.68"
bincode = "1.2.1"