[package]
name = "wasm_string_test"
version = "0.1.0"
authors = ["mvidigueira <mvidigueira@gmail.com>"]
edition = "2018"

[lib]
crate-type = ['cdylib']

[dependencies]
wasm-bindgen = "=0.2.54"
wasm_contracts_common = {path="../wasm_contracts_common"}
bincode = "1.2.1"
base64 = "0.11.0"
