[package]
name = "wasm_common_bindings"
version = "0.1.0"
authors = ["mvidigueira <mvidigueira@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "=1.2.1"
serde = { version = "1.0"}

[dependencies.ed25519-dalek]
version = "1.0.1"
features = ["serde"]